### ISSUE TITLE
Setup auto deploy

### ISSUE THREAD

**Issue by tranchien2002** [tranchien2002/tomoGameFrontend#36]

**Comment by vinhyenvodoi98** [comment]
research Github auto deployment https://developer.github.com/v3/guides/delivering-deployments/

**Comment by vinhyenvodoi98** [comment]
research FramgiaCI/CD https://civ3.sun-asterisk.vn/document

**Comment by vinhyenvodoi98** [comment]
i have error with pip ,can't install framgia-ci 
hướng dẫn download tại [đây](https://github.com/framgia/ci-report-tool)
framgia-ci.yml
```
project_type: javascript
build:
  unit_test:
    image: node:8-slim
    prepare:
      - yarn --no-progress install --pure-lockfile
      - framgia-ci run --logs
test:
  npm:
    ignore: false
    command: npm test

deploy:
  dev_server:
    when:
      branch: master
    run: yarn deploy
cache:
  nodejs:
    folder: node_modules
    file: yarn.lock
```
